/**
 * Maps a Language.code to a representative country flag emoji, purely
 * on the frontend — no DB column/migration needed for this. Kurdish
 * has no ISO country and therefore no flag emoji at all, so it's
 * handled separately (see components/shared/LanguageFlag.tsx, which
 * renders the Kurdistan flag as inline SVG instead).
 */
export const KURDISH_CODES = new Set(["kmr-badini", "ckb", "kmr"]);

export const LANGUAGE_FLAGS: Record<string, string> = {
  tr: "🇹🇷",
  en: "🇬🇧",
  ar: "🇸🇦",
  fa: "🇮🇷",
  es: "🇪🇸",
  fr: "🇫🇷",
  de: "🇩🇪",
  it: "🇮🇹",
  ru: "🇷🇺",
  ja: "🇯🇵",
  ko: "🇰🇷",
  zh: "🇨🇳",
  hi: "🇮🇳",
  ur: "🇵🇰",
  pt: "🇵🇹",
  nl: "🇳🇱",
  sv: "🇸🇪",
  no: "🇳🇴",
  da: "🇩🇰",
  fi: "🇫🇮",
  pl: "🇵🇱",
  uk: "🇺🇦",
  cs: "🇨🇿",
  sk: "🇸🇰",
  ro: "🇷🇴",
  hu: "🇭🇺",
  bg: "🇧🇬",
  sr: "🇷🇸",
  hr: "🇭🇷",
  bs: "🇧🇦",
  sl: "🇸🇮",
  sq: "🇦🇱",
  el: "🇬🇷",
  he: "🇮🇱",
  lt: "🇱🇹",
  lv: "🇱🇻",
  et: "🇪🇪",
  is: "🇮🇸",
  ga: "🇮🇪",
  cy: "🇬🇧",
  ca: "🇪🇸",
  eu: "🇪🇸",
  gl: "🇪🇸",
  af: "🇿🇦",
  sw: "🇹🇿",
  am: "🇪🇹",
  ha: "🇳🇬",
  yo: "🇳🇬",
  ig: "🇳🇬",
  zu: "🇿🇦",
  so: "🇸🇴",
  mg: "🇲🇬",
  vi: "🇻🇳",
  th: "🇹🇭",
  id: "🇮🇩",
  ms: "🇲🇾",
  tl: "🇵🇭",
  km: "🇰🇭",
  lo: "🇱🇦",
  my: "🇲🇲",
  ne: "🇳🇵",
  si: "🇱🇰",
  bn: "🇧🇩",
  pa: "🇮🇳",
  ta: "🇮🇳",
  te: "🇮🇳",
  ml: "🇮🇳",
  mr: "🇮🇳",
  gu: "🇮🇳",
  kn: "🇮🇳",
  ps: "🇦🇫",
  prs: "🇦🇫",
  az: "🇦🇿",
  uz: "🇺🇿",
  kk: "🇰🇿",
  ky: "🇰🇬",
  mn: "🇲🇳",
  ka: "🇬🇪",
  hy: "🇦🇲",
  yue: "🇭🇰",
  ht: "🇭🇹",
};

/** Emoji-only flag lookup — safe to use inside a plain <option> text node. */
export function flagEmoji(code: string): string {
  if (KURDISH_CODES.has(code)) return "🏔️";
  return LANGUAGE_FLAGS[code] ?? "🌐";
}
