/**
 * ONE-OFF LOAD-TEST UTILITY — not a seeding script, not for
 * production content. Creates a batch of throwaway "loadtest_*"
 * users + posts directly in the database (bypassing Supabase Auth
 * entirely — public.users has no hard FK to auth.users, see
 * prisma/sql/00_auth_trigger.sql, the same trick
 * prisma/sql/04_grant_premium.sql relies on), times how the app's
 * real hot-path queries behave with that much more data in the
 * tables, then DELETES every row it created — cascades to their
 * posts/likes/etc. per schema.prisma's onDelete: Cascade — so nothing
 * fake is ever left behind for a real user to see. Cleanup runs in a
 * finally block, so it still happens even if a timing query throws.
 *
 * Run with:  npx tsx scripts/loadtest.ts [count]
 *   count defaults to 500 (Dilva mentioned wanting to see behaviour
 *   around 600-850 registered users).
 *
 * IMPORTANT — this project's Supabase connection goes through a
 * pooler with connection_limit=1 (see lib/prisma.ts and the comments
 * throughout the API routes). This script competes for that same one
 * connection like everything else, so:
 *   - Run it when there's little/no real traffic on the site.
 *   - It uses createMany (bulk inserts) instead of a per-row loop —
 *     a handful of round trips total regardless of `count` — for the
 *     same reason every bulk admin operation in this app does.
 *   - If it's ever run against a database with real users, it still
 *     never touches their rows — only the "loadtest_*" usernames it
 *     creates itself.
 */
import { PrismaClient } from "@prisma/client";
import { randomUUID } from "node:crypto";

const prisma = new PrismaClient();

const COUNT = Number(process.argv[2] ?? 500);

// Rough bounding boxes for Iraq, Turkey and Iran — random points
// inside these just need to be realistic enough for query timing
// (distance math, indexes), not precisely on land.
const REGIONS = [
  { country: "Iraq", city: "Duhok", minLat: 29.0, maxLat: 37.3, minLng: 38.8, maxLng: 48.5 },
  { country: "Turkey", city: "Diyarbakır", minLat: 36.0, maxLat: 42.0, minLng: 26.0, maxLng: 45.0 },
  { country: "Iran", city: "Urmia", minLat: 25.0, maxLat: 39.7, minLng: 44.0, maxLng: 63.3 },
];

function randomIn(min: number, max: number): number {
  return min + Math.random() * (max - min);
}

async function timeQuery(label: string, fn: () => Promise<unknown>) {
  const start = Date.now();
  const result = await fn();
  const ms = Date.now() - start;
  const count = Array.isArray(result) ? result.length : typeof result === "number" ? result : undefined;
  console.log(`  ${label}: ${count !== undefined ? `${count} rows, ` : ""}${ms}ms`);
}

async function main() {
  console.log(`Creating ${COUNT} throwaway "loadtest_*" users (Iraq/Turkey/Iran)...`);

  const runTag = Date.now();
  const userIds: string[] = [];
  const userRows = Array.from({ length: COUNT }, (_, i) => {
    const id = randomUUID();
    userIds.push(id);
    const region = REGIONS[i % REGIONS.length];
    return {
      id,
      username: `loadtest_${runTag}_${i}`,
      displayName: `Load Test ${i}`,
      country: region.country,
      city: region.city,
      latitude: randomIn(region.minLat, region.maxLat),
      longitude: randomIn(region.minLng, region.maxLng),
      isLocationVisible: true,
    };
  });
  await prisma.user.createMany({ data: userRows });

  console.log("Creating 2 posts per user...");
  const postRows = userIds.flatMap((authorId, i) => [
    { authorId, content: `[loadtest ${runTag}] post ${i}-a — safe to delete, generated by scripts/loadtest.ts` },
    { authorId, content: `[loadtest ${runTag}] post ${i}-b — safe to delete, generated by scripts/loadtest.ts` },
  ]);
  await prisma.post.createMany({ data: postRows });

  try {
    console.log("\nTiming real hot-path queries against the inflated tables:");

    await timeQuery("total user count", () => prisma.user.count());
    await timeQuery("total post count", () => prisma.post.count());

    await timeQuery("feed-style query (50 latest posts, author included)", () =>
      prisma.post.findMany({
        orderBy: { createdAt: "desc" },
        take: 50,
        include: { author: { select: { username: true, displayName: true, avatarUrl: true } } },
      })
    );

    await timeQuery("nearby-style raw distance query (same shape as lib/geo.ts)", () =>
      prisma.$queryRaw`
        SELECT "id",
          (6371 * acos(LEAST(1.0, GREATEST(-1.0,
            cos(radians(36.86)) * cos(radians("latitude")) * cos(radians("longitude") - radians(42.99)) +
            sin(radians(36.86)) * sin(radians("latitude"))
          )))) AS "distanceKm"
        FROM "users"
        WHERE "isLocationVisible" = true AND "latitude" IS NOT NULL AND "longitude" IS NOT NULL
        ORDER BY "distanceKm" ASC
        LIMIT 50;
      `
    );

    await timeQuery("admin-style groupBy (users by country)", () =>
      prisma.user.groupBy({ by: ["country"], _count: { _all: true } })
    );
  } finally {
    console.log("\nCleaning up — deleting every loadtest user (cascades to their posts)...");
    const deleted = await prisma.user.deleteMany({ where: { id: { in: userIds } } });
    console.log(`Deleted ${deleted.count} loadtest users. Nothing fake left behind.`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
